In [22]:
# Testing gemmi symmetry

import gemmi
import numpy as np
import ase, ase.io
import ase.spacegroup
from plotting import plot_grid

#file = ""
#
nx ,ny, nz = 4,4,4
grid_shape = (nx, ny, nz)
gridpoint = [0,0,0]
spgrp = ase.spacegroup.Spacegroup(30)
print("spacegroup: ", spgrp)

#atoms = ase.io.read(file)
#unitcell = if atoms: 
#unitcell =

boolgrid = gemmi.Int8Grid(*grid_shape)
egrid = gemmi.FloatGrid(*grid_shape)

boolgrid.spacegroup = gemmi.find_spacegroup_by_number(spgrp)
egrid.spacegroup =  gemmi.find_spacegroup_by_number(spgrp)

boolgrid.set_size(*grid_shape)
egrid.set_size(*grid_shape)

#boolgrid.set_unitcell(unitcell)
#egrid.set_unitcell(unitcell)

boolgrid.set_value(0, 0, 0, 1)
boolgrid_init = boolgrid.clone()
# Print before
print(boolgrid_init.array)

# Print after symmetrizing
boolgrid_after = boolgrid.clone()
boolgrid_after.symmetrize_max()
print(boolgrid_after.array)


spacegroup:  30    P n c 2
  setting 1
  centrosymmetric 0
  primitive vectors
     1.0000000000  0.0000000000  0.0000000000
     0.0000000000  1.0000000000  0.0000000000
     0.0000000000  0.0000000000  1.0000000000
  reciprocal vectors
      1   0   0
      0   1   0
      0   0   1
  1 subtranslations
     0.0000000000  0.0000000000  0.0000000000
  4 symmetry operations (rot+trans)
    1  0  0     0  1  0     0  0  1    0.0000000000  0.0000000000  0.0000000000
   -1  0  0     0 -1  0     0  0  1    0.0000000000  0.0000000000  0.0000000000
    1  0  0     0 -1  0     0  0  1    0.0000000000  0.5000000000  0.5000000000
   -1  0  0     0  1  0     0  0  1    0.0000000000  0.5000000000  0.5000000000


[[[1 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
[[[1 0 0 0]
  [0 0 0 0]
  [0 0 1 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0