In [4]:
## Test of the unitcell_to_supercell_frac_coords function ## 

import preparatory_fcns
from preparatory_fcns import unitcell_to_supercell_frac_coords as us2sp_fcoord
import ase
from ase import Atoms
import numpy as np

# Make atoms object, wait why??
#atoms = Atoms('H3',[[0,0,0],[2,0,0],[0,2,0]], cell=[3,3,3], pbc=[True,True,True])

# Make fractional grid
grid  = np.array([[0,0,0],[0,0,1.5], [0,1.5,0],[0,1.5,1.5],[1.5,0,0],[1.5,0,1.5],[1.5,1.5,1.5]])
frac_grid = np.divide(grid,(3,3,3))
print(frac_grid)

# Translate the fractional coordinates of the grid to correspond to a middle unitcell in a 3x3x3 supercell
new_grid = us2sp_fcoord(frac_grid,(3,3,3))
print(new_grid)

[[0.  0.  0. ]
 [0.  0.  0.5]
 [0.  0.5 0. ]
 [0.  0.5 0.5]
 [0.5 0.  0. ]
 [0.5 0.  0.5]
 [0.5 0.5 0.5]]
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.5       ]
 [0.33333333 0.5        0.33333333]
 [0.33333333 0.5        0.5       ]
 [0.5        0.33333333 0.33333333]
 [0.5        0.33333333 0.5       ]
 [0.5        0.5        0.5       ]]


In [5]:
### TEST OF ATOM REMOVING FUNCTION 
from preparatory_fcns import remove_nonframework_cations_fancy, remove_nonframework_cations
from ase import Atom
from ase.io import read, write
from ase.io.cube import write_cube
from pathlib import Path

parent_path = Path("Melania_data")
data_path = Path(parent_path, "data_lmp")
cif_path =  Path(parent_path, 'init_cif', '54189.cif')

#with open(cif_path) as fp:
#    test_atoms = read(fp)
test_atoms = read(cif_path)

cation = Atom('Li')

catremoved_atoms_1 = remove_nonframework_cations(test_atoms, cation)
catremoved_atoms_2 = remove_nonframework_cations_fancy(test_atoms, cation)

print(test_atoms)
print(catremoved_atoms_1)
print(catremoved_atoms_2)



Atoms(symbols='Li2ZnGe', pbc=True, cell=[[4.3592827, 0.0, 0.0], [2.1796413500000003, 3.775249560478017, 0.0], [2.1796413500000003, 1.2584165201593394, 3.5593394198473853]])
Atoms(symbols='ZnGe', pbc=True, cell=[[4.3592827, 0.0, 0.0], [2.1796413500000003, 3.775249560478017, 0.0], [2.1796413500000003, 1.2584165201593394, 3.5593394198473853]])
Atoms(symbols='ZnGe', pbc=True, cell=[[4.3592827, 0.0, 0.0], [2.1796413500000003, 3.775249560478017, 0.0], [2.1796413500000003, 1.2584165201593394, 3.5593394198473853]])


In [8]:
# TEST OF FUNCTION CALCULATING THE APPROPRIATE SUPERCELL SIZE 
# FROM UNITCELL AND FORCE CUT-OFF
from preparatory_fcns import compute_req_supercells as crsp
import matplotlib.pyplot as plt

f_cutoff = 10.0

test_cell = ase.Atoms("Na4Cl4",
                        cell=np.diag([10, 10, 10]),
                        positions=[[1.0, 1.0, 1.0],
                                   [9.0, 9.0, 1.0],
                                   [9.0, 1.0, 9.0],
                                   [1.0, 9.0, 9.0],
                                   [9.0, 9.0, 9.0],
                                   [1.0, 1.0, 9.0],
                                   [1.0, 9.0, 1.0],
                                   [9.0, 1.0, 1.0]],
                        pbc=[1,1,1]
                        )

sup_cell_size = crsp(test_cell, f_cutoff)
print(sup_cell_size)
print("Spacegroup: ", ase.spacegroup.get_spacegroup(test_cell))

Hello 1
Hello 2
Hello 3
(10.0, 10.0, 10.0)
10.0
Min distance check:  10.0
3
Spacegroup:  215   P -4 3 m
  setting 1
  centrosymmetric 0
  primitive vectors
     1.0000000000  0.0000000000  0.0000000000
     0.0000000000  1.0000000000  0.0000000000
     0.0000000000  0.0000000000  1.0000000000
  reciprocal vectors
      1   0   0
      0   1   0
      0   0   1
  1 subtranslations
     0.0000000000  0.0000000000  0.0000000000
  24 symmetry operations (rot+trans)
    1  0  0     0  1  0     0  0  1    0.0000000000  0.0000000000  0.0000000000
   -1  0  0     0 -1  0     0  0  1    0.0000000000  0.0000000000  0.0000000000
   -1  0  0     0  1  0     0  0 -1    0.0000000000  0.0000000000  0.0000000000
    1  0  0     0 -1  0     0  0 -1    0.0000000000  0.0000000000  0.0000000000
    0  0  1     1  0  0     0  1  0    0.0000000000  0.0000000000  0.0000000000
    0  0  1    -1  0  0     0 -1  0    0.0000000000  0.0000000000  0.0000000000
    0  0 -1    -1  0  0     0  1  0    0.0000000000  0

AttributeError: type object 'Atom' has no attribute 'spacegroup'