In [50]:
import numpy as np
import pymatgen as pmg
from pymatgen.core import Structure, Lattice
import pymatgen.symmetry as pmgsym
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

import ase
import ase.io

file = "Melania_data/init_cif/54189.cif"
atoms = ase.io.read(file)
struct_from_file = Structure.from_file(file)
f_atomic_coords = atoms.get_scaled_positions()
atomic_symb = atoms.get_chemical_symbols()
cell_params = atoms.get_cell_lengths_and_angles()

cart_coords = atoms.get_positions()

lattice = Lattice.from_parameters(*cell_params)
struct = Structure(lattice, atomic_symb, f_atomic_coords)

sg_analyzer = SpacegroupAnalyzer(struct_from_file)

symops = sg_analyzer.get_symmetry_operations()
conventional_struct = sg_analyzer.get_conventional_standard_structure()
found_primitive = sg_analyzer.find_primitive()

pg_ops = sg_analyzer.get_point_group_operations()
spgrp_num = sg_analyzer.get_space_group_number()
spgrp_symb = sg_analyzer.get_space_group_symbol()
lattice_type = sg_analyzer.get_lattice_type()
crys_sys = sg_analyzer.get_crystal_system()

conv2prim_matrix = np.array(sg_analyzer.get_conventional_to_primitive_transformation_matrix())

print("ops same?:",pg_ops == symops)

""" This doesnt work because apparently I trnasform the matrices to np.arrays
A_c = np.array(struct.lattice)
print(A_c)
print(type(A_c))
A_p = np.array(found_primitive.lattice)
print("lattice:", A_c, A_c.shape)
print("Transformation matrix :",conv2prim_matrix)
M = A_c @ np.linalg.inv(conv2prim_matrix)
"""

#print("M matrix", M)
#print(type(symops))
#print(symops[4], type(symops[4]))
print("pg_ops:")
print(pg_ops)

elem_coords = []
temp_coord_list = []
elem_list = []

for elem in set(atomic_symb):
    elem_list.append(elem)
    for ind, a in enumerate(atomic_symb):
        if a == elem:
            temp_coord_list.append(atoms.get_scaled_positions()[ind])
    
    elem_coords.append(temp_coord_list.copy())
    temp_coord_list.clear()

print(elem_list)
print(elem_coords)
"""
elem_coords_new = []
bool_list_sg = []
for sym in symops:
    print(sym.operate_multi(atoms.get_positions()))
    print((sym.operate_multi(atoms.get_positions()) == atoms.get_positions()).all())
    elem_coords_new.append(sym.operate_multi(elem_coords[0]))
    bool_list_sg.append((sym.operate_multi(atoms.get_positions()) == atoms.get_positions()).all())

print(bool_list_sg)
"""

elem_coords_new_pg = []
bool_list_pg = []
bool_list_2_pg = []

for sym in pg_ops:
    print(atoms.get_scaled_positions())
    print(sym.operate_multi(atoms.get_scaled_positions()))
    
    print((np.abs(np.array(sym.operate_multi(atoms.get_scaled_positions())) - np.array(atoms.get_scaled_positions())) < 10**(-4)).all())
    print((np.array(sym.operate_multi(atoms.get_scaled_positions())) == np.array(atoms.get_scaled_positions())).all())
    elem_coords_new_pg.append(sym.operate_multi(elem_coords[0]))
    bool_list_2_pg.append((np.abs(np.array(sym.operate_multi(atoms.get_scaled_positions())) - np.array(atoms.get_scaled_positions())) < 10**(-4)).all())
    bool_list_pg.append((np.array(sym.operate_multi(atoms.get_scaled_positions())) == np.array(atoms.get_scaled_positions())).all())



print(bool_list_pg)
print(bool_list_2_pg)
for indx, test in enumerate(bool_list_pg):
    if test:
        print(pg_ops[indx])

for indx, test in enumerate(bool_list_2_pg):
    if test:
        print(pg_ops[indx])

ops same?: True
pg_ops:
[Rot:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
tau
[0. 0. 0.], Rot:
[[ 0.  1.  0.]
 [-1. -1. -1.]
 [ 1.  0.  0.]]
tau
[0. 0. 0.], Rot:
[[-1. -1. -1.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]
tau
[0. 0. 0.], Rot:
[[ 0.  0.  1.]
 [ 1.  0.  0.]
 [-1. -1. -1.]]
tau
[0. 0. 0.], Rot:
[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [-1. -1. -1.]]
tau
[0. 0. 0.], Rot:
[[-1. -1. -1.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.], Rot:
[[ 0.  0.  1.]
 [-1. -1. -1.]
 [ 1.  0.  0.]]
tau
[0. 0. 0.], Rot:
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
tau
[0. 0. 0.], Rot:
[[ 0.  0.  1.]
 [ 0.  1.  0.]
 [-1. -1. -1.]]
tau
[0. 0. 0.], Rot:
[[ 1.  0.  0.]
 [-1. -1. -1.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.], Rot:
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
tau
[0. 0. 0.], Rot:
[[-1. -1. -1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]]
tau
[0. 0. 0.], Rot:
[[-1. -1. -1.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.], Rot:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
tau
[0. 0. 0.], Rot:
[[ 1.  0.  0.]
 [-1. -1. -1.]
 [ 0.  1.  0.]]
tau
[0. 0. 0.], Rot:
[